export const BUILDINGS = [
  {
    id: '1',
    name: 'Catedrala Mitropolitană',
    shortName: 'Catedrala',
    year: '1936–1946',
    architect: 'Ion Traianescu',
    style: 'Neo-Bizantin',
    tag: 'Patrimoniu Religios',
    distance: '5 m',
    bearing: 'N',
    rating: 4.9,
    accent: '#FFB26B',
    coordinates: { lat: 45.7489, lng: 21.2087 },
    facts: [
      'Cel mai înalt monument din Timișoara — 83,7 m înălțime cu tot cu cruce.',
      'A fost construită în stilul bisericilor moldovenești din sec. XV–XVI.',
      'Catapeteasma este sculptată în lemn de tei și acoperită cu foiță de aur.',
    ],
    blurb:
      'Simbol al Timișoarei și al credinței ortodoxe bănățene, catedrala domină Piața Victoriei și a devenit un reper vizual al orașului european al culturii 2023.',
  },
  {
    id: '2',
    name: 'Opera Națională',
    shortName: 'Opera',
    year: '1875',
    architect: 'Fellner & Helmer',
    style: 'Baroc Vienez',
    tag: 'Monument Istoric',
    distance: '22 m',
    bearing: 'V',
    rating: 4.8,
    accent: '#8BD3FF',
    coordinates: { lat: 45.7494, lng: 21.2073 },
    facts: [
      'Construită de celebra firmă vieneză Fellner & Helmer, autoare a peste 48 de teatre europene.',
      'Sala mare are 934 de locuri și o acustică remarcabilă.',
      'Fațada este decorată cu statui alegorice reprezentând muzica și drama.',
    ],
    blurb:
      'Situată față în față cu Catedrala Mitropolitană pe Piața Victoriei, Opera Națională din Timișoara este una dintre cele mai elegante clădiri de spectacol din România.',
  },
  {
    id: '3',
    name: 'Castelul Huniade',
    shortName: 'Castelul',
    year: 'sec. XIV',
    architect: 'Iancu de Hunedoara',
    style: 'Gotic Medieval',
    tag: 'Monument Istoric',
    distance: '340 m',
    bearing: 'E',
    rating: 4.7,
    accent: '#B8F0C2',
    coordinates: { lat: 45.7457, lng: 21.2262 },
    facts: [
      'A fost reședința lui Iancu de Hunedoara, guvernatorul Ungariei în sec. XV.',
      'Adăpostește Muzeul Banatului, cu peste 1,7 milioane de obiecte de patrimoniu.',
      'A suferit incendii majore în 1443 și 1849, de fiecare dată fiind reconstruit.',
    ],
    blurb:
      'Cel mai vechi monument medieval păstrat din Timișoara, construit inițial în stil gotic și extins de-a lungul secolelor. Astăzi este sediul Muzeului Banatului.',
  },
  {
    id: '4',
    name: 'Catedrala Romano-Catolică',
    shortName: 'Dom-ul',
    year: '1736–1754',
    architect: 'Joseph E. Fischer von Erlach',
    style: 'Baroc Imperial',
    tag: 'Patrimoniu Religios',
    distance: '1,1 km',
    bearing: 'NE',
    rating: 4.6,
    accent: '#E1B9FF',
    coordinates: { lat: 45.7578, lng: 21.2283 },
    facts: [
      'Este una dintre cele mai importante clădiri baroce din România.',
      'Construită după planurile arhitectului imperial vienez, sub patronajul lui Carol VI.',
      'Pictura interioară a bolții a fost realizată de Frantz Anton Maulbertsch.',
    ],
    blurb:
      'Dom-ul catolic din Piața Unirii este vârful stilului baroc în Timișoara, construit în perioada dominației habsburgice și dedicat Sfântului Gheorghe.',
  },
];
