// Building data + shared tokens

const buildings = [
  {
    id: 1,
    name: "Palatul Parlamentului",
    shortName: "Parlament",
    year: "1984–1997",
    architect: "Anca Petrescu",
    style: "Realism Socialist",
    tag: "Clădire Administrativă",
    distance: "12 m",
    bearing: "NV",
    rating: 4.8,
    accent: "#FFB26B",
    facts: [
      "Al doilea cea mai mare clădire administrativă din lume, după Pentagonul SUA.",
      "1.100 de camere distribuite pe 12 niveluri suprateran și 8 subterane.",
      "Construcția a implicat 20.000 de muncitori și 700 de arhitecți.",
    ],
    blurb: "Ridicată la comanda lui Nicolae Ceaușescu, clădirea este un simbol controversat al epocii comuniste și găzduiește astăzi Camera Deputaților și Senatul României.",
  },
  {
    id: 2,
    name: "Ateneul Român",
    shortName: "Ateneul",
    year: "1888",
    architect: "Albert Galleron",
    style: "Neoclasic",
    tag: "Patrimoniu UNESCO",
    distance: "34 m",
    bearing: "E",
    rating: 4.9,
    accent: "#8BD3FF",
    facts: [
      "Construit prin donații publice — campania „Dați un leu pentru Ateneu”.",
      "Sala mare are o acustică considerată printre cele mai bune din Europa.",
      "Frescă interioară de 75 m lungime ilustrând istoria României.",
    ],
    blurb: "Inima muzicii clasice românești și sediul Filarmonicii „George Enescu”. Domul de 41 m înălțime este un reper al Pieței George Enescu.",
  },
  {
    id: 3,
    name: "Turnul Colțea",
    shortName: "Colțea",
    year: "1715",
    architect: "Necunoscut",
    style: "Brâncovenesc",
    tag: "Monument Istoric",
    distance: "8 m",
    bearing: "S",
    rating: 4.5,
    accent: "#B8F0C2",
    facts: [
      "A fost cel mai înalt punct al Bucureștiului până în secolul al XIX-lea.",
      "Reconstruit de mai multe ori după cutremure și incendii.",
      "Are 25 de metri înălțime și a servit drept foișor de foc.",
    ],
    blurb: "Parte a ansamblului Spitalului Colțea, turnul este unul dintre puținele monumente păstrate din perioada brâncovenească în București.",
  },
  {
    id: 4,
    name: "CEC Palace",
    shortName: "CEC",
    year: "1900",
    architect: "Paul Gottereau",
    style: "Eclectic francez",
    tag: "Monument Istoric",
    distance: "58 m",
    bearing: "V",
    rating: 4.7,
    accent: "#E1B9FF",
    facts: [
      "Cupolă de sticlă și metal, 25 m diametru, o performanță tehnică a epocii.",
      "Construit pe locul fostei mănăstiri Sfântul Ioan cel Mare.",
      "A fost sediul Casei de Economii și Consemnațiuni din 1900.",
    ],
    blurb: "Considerat una dintre cele mai frumoase clădiri de pe Calea Victoriei, fațada sa eclectică amintește de arhitectura pariziană Belle Époque.",
  },
];

const tokens = {
  bg: '#07070a',
  bgDeep: '#000',
  panel: 'rgba(10, 14, 22, 0.82)',
  panelSolid: '#0c1017',
  border: 'rgba(255,255,255,0.08)',
  borderStrong: 'rgba(255,255,255,0.16)',
  accent: '#5EFCCF',
  accentDim: 'rgba(94,252,207,0.18)',
  text: '#F2F5F7',
  textDim: 'rgba(235,238,245,0.62)',
  textMuted: 'rgba(235,238,245,0.38)',
  warn: '#FFB26B',
  danger: '#FF6B8B',
  mono: "'JetBrains Mono', ui-monospace, monospace",
  display: "'Orbitron', 'Inter', system-ui, sans-serif",
  body: "'Inter', system-ui, sans-serif",
};

Object.assign(window, { buildings, tokens });
